# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 12:42
from __future__ import unicode_literals

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170702_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.user_path),
        ),
    ]
